import type { LegalTerm } from "../page";

export const LEGAL_TERMS: LegalTerm[] = [
  { term: "abandon", definition: "v.tointentionally and permanently give up,surrender, leave, desert orrelinquish allin- terest orownership inproperty, a home orother premises, aright of way,andeven aspouse, family, or children. Theword isoften used in situations todetermine whether a tenant has lefhis/her apartment andtheproperty inside anddoes notintend tocome back. Thus, a landlord cantake overanappar- ently abandoned residence, but must store anything atenant leaves behind andgive notice to thetenant before selling thepos- sessions which are left.Toaban- donchildren canmean tohaveno contact andgivenosupport fora year ormore. (See:abandoned property, abandonment)" },
  { term: "abandoned property", definition: "n.property leftbehind (often byatenant) in- tentionally andpermanently when itappears that theformer owner (ortenant) doesnotintend tocome back, pick itup,oruse it.Examples may include possessions leftina house after thetenant hasmoved outorautos leftbeside aroad fora longperiod oftime, orpatent rights ofaninventor whodoes notapply forapatent andletsothers usehis invention without protest. One mayhaveabandoned theproperty ofcontract rights bynotdoingwhat isrequired bythecontract. Howev- er,aneasement andother land rights arenotabandoned property just because ofnon-use. (See: abandon, abandonment)abandonment: n.theactofintention- allyandpermanently giving up,sur- rendering, deserting orrelinquishing property, premises, aright ofway, a ship, contract rights, aspouse and/or children. Abandonment ofaspouse means intent atpermanent separa- tion,andwith children alengthy peri- odofneither contact noranysupport. Inmaritime lawabandonment hasa" },
  { term: "special meaning", definition: "when anowner sur- renders ashipand itscontents toa trustee forthebenefit ofclaimants, particularly after awreck. Ifone in- vents something anddoes notgeta patent butallows others tousethein- vention ordedicates ittopublic use, theright topatent isprobably aban- doned. Confusion arises over aban- donment ofwater rights, mining rights, orrights ofway, since mere non-use isnotsufficient toshow aban- donment. (See: abandon, aban- doned property, patent)" },
  { term: "abate", definition: "v.todoaway with aproblem, such asapublic orprivate nuisance or some structure builtcontrary topublic policy. Thiscaninclude dikeswhich il- legally direct water onto aneighbor's property, highvolume noise from a rockband orafactory, animprove- ment constructed inviolation ofbuild- ingandsafety codes, orseepage froma faulty septic tank. (See:abatement)" },
  { term: "abatement", definition: "n.1)theremoval ofaprob- lemwhich isagainst public orprivate policy, orendangers others, including nuisances such asweeds thatmight catch fireonanotherwise empty lot; 2)anequal reduction ofrecovery of 18 abortion debts byallcreditors when there arenotenough funds orassets to paythefullamount; 3)anequal re- duction ofbenefits tobeneficiaries (heirs) when anestate isnotlarge enough topayeach beneficiary in full. (See:abate)" },
// ... (truncated for brevity, but the full array will be pasted here)
]; 